[package]
name = "helper"
description = "test helper utils for the undis crate"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.14", features = ["rt"] }
undis = { path = ".." }
